{{- if .Values.secrets.GCPServiceAccount -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp-emulator.fullname" . }}-sa
  labels:
{{ include "gcp-emulator.labels" . | nindent 4 }}
type: Opaque
data: 
{{ (.Files.Glob "serviceaccount/key.json").AsSecrets | indent 2 }}
{{- end -}}
