{{- if .Values.secrets.create -}}
apiVersion: v1
data:
  {{ range $key, $value := .Values.secrets.vars -}}
    {{ base $key }}: {{ $value | b64enc }} 
  {{ end }}
kind: Secret
metadata:
  labels:
    {{- include "gcp-emulator.labels" . | nindent 4 }}
  name: {{ include "gcp-emulator.fullname" . }}
type: Opaque
{{- end -}}
