{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcp-emulator.serviceAccountName" . }}
  labels:
{{ include "gcp-emulator.labels" . | nindent 4 }}
{{- end -}}
