apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcp-emulator.fullname" . }}
  labels:
    {{- include "gcp-emulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "gcp-emulator.selectorLabels" . | nindent 4 }}
